# Generated by Django 5.2.10 on 2026-01-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('VIEWER', 'Viewer')], default='SUPERVISOR', max_length=20),
        ),
    ]
