# Generated by Django 5.2.10 on 2026-01-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('tasks', '0003_milestone_completed_by_milestone_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectmember'),
        ),
        migrations.AlterUniqueTogether(
            name='taskmember',
            unique_together={('task', 'user')},
        ),
    ]
